# Generated by Django 4.1.1 on 2022-09-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_elixir', '0002_alter_photo_date_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='last_shown',
            field=models.DateField(blank=True, null=True),
        ),
    ]
